name: Auto-Merge v2-dev to master

on:
  schedule:
    - cron: '0 1 * * *'  # Runs daily at 1 AM UTC. Adjust as needed.
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Important: Fetch full history for accurate diffs

      - name: Check for changes
        id: check_changes
        run: |
          if git diff --quiet master...v2-dev; then
            echo "::set-output name=changes::false"
          else
            echo "::set-output name=changes::true"
          fi
      - name: Create Pull Request
        if: steps.check_changes.outputs.changes == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'Auto-merge v2-dev to master'
          title: 'Auto-merge v2-dev to master'
          body: |
            This pull request is automatically generated by GitHub Actions.
            It merges changes from the `v2-dev` branch into the `master` branch.
          base: master
          head: v2-dev
          draft: false # Set to true to create a draft PR

      - name: Auto-Merge Pull Request
        if: steps.check_changes.outputs.changes == 'true'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { owner, repo } = context.repo;
            const pr = context.payload.pull_request;
            if (!pr) {
              console.log("No pull request found in context.");
              return;
            }
            const { data: pullRequest } = await github.rest.pulls.get({
              owner,
              repo,
              pull_number: pr.number,
            });
            if (pullRequest.merged) {
              console.log("Pull request already merged.");
              return;
            }
            if (pullRequest.mergeable && pullRequest.review_approved) {
              await github.rest.pulls.merge({
                owner,
                repo,
                pull_number: pr.number,
              });
              console.log("Pull request merged automatically.");
            } else {
              console.log("Pull request not mergeable or not approved.  Skipping auto-merge.");
            }
