name: 2. Manual Merge v2-dev to Master (For Deploy)

on:
  workflow_dispatch: # ต้องกดปุ่ม 'Run workflow' ด้วยตนเองเท่านั้น

jobs:
  merge:
    runs-on: ubuntu-latest
    permissions:
      contents: write # จำเป็นสำหรับการ push กลับไปยัง master ของคุณ

    steps:
      - name: Checkout your master branch (Target)
        uses: actions/checkout@v4
        with:
          ref: master # 1. เราเริ่มต้นด้วยการ Checkout สาขา 'master' ของคุณ
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set Git identity
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
      - name: Add upstream remote (enricoros)
        run: git remote add upstream https://github.com/enricoros/big-AGI.git

      - name: Fetch all remotes
        run: |
          git fetch upstream
          git fetch origin # ดึงข้อมูลสาขาล่าสุดจาก Fork ของเราเอง (รวมถึง v2-dev)

      - name: Merge origin/v2-dev into master
        run: |
          git checkout master
          
          # 2. สั่ง Merge โดยดึงการเปลี่ยนแปลงจาก 'origin/v2-dev' (v2-dev ของคุณ) เข้ามาใน 'master'
          # ใช้ --no-ff เพื่อให้เกิด Merge Commit ชัดเจน
          echo "Attempting to merge origin/v2-dev into master..."
          git merge origin/v2-dev --no-ff
          
      - name: Check for Merge Conflicts
        id: check_conflict
        run: |
          # ตรวจสอบว่ามีการ Conflict หรือไม่
          if git diff --quiet; then
            echo "merge_status=success" >> $GITHUB_OUTPUT
          else
            echo "merge_status=conflict" >> $GITHUB_OUTPUT
            echo "::error::Merge conflict detected when merging origin/v2-dev to master! Please resolve manually."
            exit 1 # หยุดการทำงานหากมี Conflict
          fi

      - name: Push merged changes to master
        if: steps.check_conflict.outputs.merge_status == 'success'
        run: |
          echo "Pushing merged changes to origin/master for Vercel deployment..."
          git push origin master
