name: Sync Fork from big-AGI v2-dev

on:
  schedule:
    - cron: '0 0 * * *'   # รันทุกวัน 00:00 UTC (07:00 เวลาไทย)
  workflow_dispatch:       # เผื่อกด manual เองได้

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout your fork
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Set Git identity
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add upstream remote
        run: git remote add upstream https://github.com/enricoros/big-AGI.git

      - name: Fetch upstream
        run: git fetch upstream

      - name: Merge upstream/v2-dev into your main
        run: |
          git checkout main
          git merge upstream/v2-dev || true

      - name: Push changes to your fork
        run: git push origin main
